[package]
name = "frieda"
version = "0.1.0"
edition = "2021"
description = "FRI-based Data Availability sampling library based on the FRIDA paper"
license = "MIT"
repository = "https://github.com/AbdelStark/frieda"
keywords = ["cryptography", "data-availability", "fri", "erasure-coding"]
categories = ["cryptography", "algorithms", "no-std"]

[dependencies]
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "19d12d7", default-features = false }
thiserror = "1.0"
num-traits = "0.2"
bitvec = "1.0.1"

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "commit"
harness = false
path = "benches/commit.rs"

[[bench]]
name = "proof"
harness = false
path = "benches/proof.rs"

[features]
default = ["std"]
std = []
