name: Benchmark

on:
  push:
    branches: ["main"]

jobs:
  benchmark:
    name: Performance benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2

      - name: Run benchmark
        run: cargo bench --all-features
