name: Benchmark

on:
  push:
    branches: [ "main" ]

jobs:
  benchmark:
    name: Performance benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # The rust-toolchain.toml in the repo will be used
      - uses: Swatinem/rust-cache@v2
      
      - name: Run benchmark
        run: cargo bench --all-features
        
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@AbdelStark'